### ISSUE TITLE
SUGGESTION - parrying should stun mobs

### ISSUE THREAD

**Issue by Cm4nXD** [Team-Abode/guarding#4]
You should add a stun mechanic to the parrying effect. similar to how the game valheim works? In adition to knockback (or instead of) the mob could be unable to move for a second or so giving you an extra window to attack without being hit. this would work great with mods like better combat and RPG difficulty.

**Comment by devesal** [comment]
I second this

**Comment by ExDrill** [comment]
I'm against adding this since it would take away a lot of skill from the parry, in other games, the whole point is to provide a minor edge, allowing the player to follow up with an attack or combo. Stunning a mob/player would make it too easy and obvious. Also, keep in mind that both of the enchantments present in Guarding benefit parrying.

**Comment by Keaton42** [comment]
Config is always an option. I respect your decision though.
